import "./globals.css";
import Navbar from "@/components/common/navbar";
import Footer from "@/components/common/footer";
import MainLayout from "@/components/layouts/MainLayout";
import { AuthProvider } from "@/context/AuthContext";
import{Toaster} from "react-hot-toast";

export const metadata = {
  title: "Royal Palms Hotel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Navbar />

          <MainLayout>
            {/* resort-style background */}
            <div className="min-h-screen bg-resort-bg bg-cover bg-center bg-no-repeat">
              <div className="bg-white/10 min-h-screen">
                {children}
                <Toaster position="top-right" />
              </div>
            </div>

            <Footer />
          </MainLayout>
        </AuthProvider>
      </body>
    </html>
  );
}
